service: product-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

custom:
  webpack:
    packager: yarn

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev

functions:
  getProductsById:
    handler: src/functions/getProductsById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  getProductsList:
    handler: src/functions/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: get
