service: product-service

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  bundle:
    ignorePackages:
      - pg-native

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors:
      allowedOrigins:
        - https://dys3ug6jzmiuj.cloudfront.net
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
      - GET
      - POST

functions:
  createProduct:
    handler: src/functions/createNewProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
  getProductsById:
    handler: src/functions/getProductsById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  getProductsList:
    handler: src/functions/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: get
