service: import-service

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  client:
    bucketName: rs-node-aws-import-bucket

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_URL:
      Ref: SNSTopic
  httpApi:
    cors:
      allowedOrigins:
        - https://dys3ug6jzmiuj.cloudfront.net
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
           - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:custom.client.bucketName}/*
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${self:custom.client.bucketName}/*
        - Effect: Allow
          Action: sqs:*
          Resource:
            Fn::GetAtt: [SQSQueue, Arn]
        - Effect: Allow
          Action: sns:*
          Resource:
            - Ref: SNSTopic

functions:
  importProductsFile:
    handler: src/functions/importProductsFile.handler
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/functions/importFileParser.handler
    events:
      - s3:
          bucket: ${self:custom.client.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
  catalogBatchProcess:
    handler: src/functions/catalogBatchProcess.handler
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt: [SQSQueue, Arn]
